function [FileParams, SpectrogramParams, AlgParams1, AlgParams2] = get_params

FileParams = struct( ...
    'audioPath', 'C:\Dror\Dolphins\Data\5th_DCL_data_common', ...
    'groundTruthClustersPath', 'C:\Dror\Dolphins\manual_tagging', ...
    'trackersDir', 'Delphinus_delphis', ...
    'trackersPath', 'C:\Dror\SpectralPeaksMeasurementSets_for_DolphinWhistles\Interpolated_Ground_Truth', ...
    'ZsetPath', 'C:\Dror\SpectralPeaksMeasurementSets_for_DolphinWhistles\Measurement_sets_MATfiles');

SpectrogramParams = struct(... % Parameters of [Gillespie et al 2013]
    'medfiltLen', 61, ... % samples --> 5719 Hz
    'winLen', 2048, ...
    'nfft', 2048, ....
    'ovp', round(2048/2));

% --- SNR detection algorithm ----
AlgParams1 = struct( ...
    'medfiltLen', 60, ... % fractional-domain samples
    'minSearchRange', 30, .... % fractional-domain samples
    'snrThd', 10); % [dB]

% --- z-score detection algorithm ---
AlgParams2 = struct( ...
    'minSearchRange', 30, .... % fractional-domain samples
    'maxNumberOfOutliers', 2, ... % maximal number of outliers to consider a valid scenario
    'stdThd', 3); % detection threshold - standard deviations

